import Head from 'next/head'
import Header from "../components/header";
import Navbar from "../components/nav";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/*Header*/}
        <Header />
        {/*Navbar*/}
        <Navbar />
        {/*Footer*/}
    </div>
  )
}
