import Head from 'next/head'
import Header from "../components/header";
import Navbar from "../components/nav";
import Results from "../components/results";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div className="">
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/*Header*/}
        <Header />
        {/*Navbar*/}
        <Navbar />
        {/*Body*/}
        <Results results={results}/>
        {/*Footer*/}
    </div>
  )
}
export async function getServerSideProps(context){
  const genre = context.query.genre;

  const request = await fetch(
      `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).then(res => res.json());
  return {
    props: {
      results: request.results,
    }
  };
}